name: Host Angular app in GitHub 
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJs 
        uses: actions/setup-node@v3.5.1
        
      - name: Install
        run: npm install
      
      - name: Test
        run: npm run test:prod
      
      - name: Lint
        run: npm lint
        
      - name: Build
        run: npm build
        
      
        
  
     
